[tool.poetry]
name = "flask-api"
version = "0.1.0"
description = ""
authors = ["devCharles <carlos.silva@yellowme.mx>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
gunicorn = "^20.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
